### ISSUE TITLE
define route error

### ISSUE THREAD

**Issue by shifengbin** [lukepighetti/fluro#193] opened 2020-10-29 03:05 UTC
Compiler message:
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn%2547/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none
          ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/pages.dart:52:3: Context: Found this candidate, but the arguments don't match.
  PageRouteBuilder({
  ^^^^^^^^^^^^^^^^

Is it not support new flutter version?

**Comment by liuxiaobina** [comment] 2020-10-30 02:01
me too

**Comment by liuxiaobina** [comment] 2020-10-30 02:01
me too      ,   updated   v1.7.6

**Comment by lukepighetti** [comment] 2020-10-30 16:39
Closing as duplicate of https://github.com/lukepighetti/fluro/issues/190

**Closed** 2020-10-30 16:40 UTC

**Comment by getpu** [comment] 2020-11-01 04:56
> Compiler message:
> ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn%2547/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
> reverseTransitionDuration: transition == TransitionType.none
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../flutter/packages/flutter/lib/src/widgets/pages.dart:52:3: Context: Found this candidate, but the arguments don't match.
> PageRouteBuilder({
> ^^^^^^^^^^^^^^^^
> 
> Is it not support new flutter version?

yes, version 1.20 , i have equal question, update version 1.22.2 stable to solve the problem.
