### ISSUE TITLE
Navigator doesnt use route generator from function

### ISSUE THREAD

**Issue by ibrokemypie** [lukepighetti/fluro#82] opened 2019-01-17 15:50 UTC
I have in my main dart file the definitions of my routes, materialapp and route generator. One route, which does work, has a button which calls a function from another file, passing in the build context. In that function it eventually calls Navigator.pushNamed(), however when it does so, it doesnt seem to use the route generator, soo doesnt find the route.

**Comment by lukepighetti** [comment] 2020-10-16 02:40
Closing because I cannot reproduce this

**Closed by lukepighetti** 2020-10-16 02:40 UTC
