### ISSUE TITLE
Error: 'dependOnInheritedWidgetOfExactType' was called on null

### ISSUE THREAD

**Issue by smkhalsa** [lukepighetti/fluro#154] opened 2020-03-25 20:23 UTC
I'm getting the following error when calling the `Router.generator` method:

```
The following NoSuchMethodError was thrown building IconTheme(color: Color(0xdd000000)):
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>()

The relevant error-causing widget was
    MaterialApp 
lib/app.dart:30
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      Theme.of 
package:flutter/…/material/theme.dart:128
#2      Router.matchRoute.<anonymous closure> 
package:fluro/src/router.dart:130
#3      Router.matchRoute 
package:fluro/src/router.dart:183
#4      Router.generator
```

It looks like [this](https://github.com/flutter/flutter/pull/44189/files#diff-de3d0ef53ebc493879548de6e9332bc9R128) change may be the source of the bug.

Is there a reason that `null` is passed for `BuildContext` [here](https://github.com/theyakka/fluro/blob/master/lib/src/router.dart#L223)?

**Comment by fatimahossny** [comment] 2020-03-26 20:34
I got this err to when I applyed` transitionType: TransitionType.native ` in the example existed with fluro package .
![Screenshot from 2020-03-26 22-33-30](https://user-images.githubusercontent.com/21333166/77693957-e760d980-6fb1-11ea-97a3-caacd3f128ea.png)

**Comment by jlubeck** [comment] 2020-04-08 14:12
I'm getting this on web when going straight to a page that is not the initial route

**Comment by smasinde** [comment] 2020-04-08 16:26
This was also happening to me when my initial route was not "/". Changed that and all good. 🤷🏾‍♂️

**Comment by zinwalin** [comment] 2020-04-24 09:23
same here. 

| JPUSH | Flutter | setup:
| JPUSH | Flutter | applyPushAuthority:
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building IconTheme(color: Color(0xdd000000)):
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>()

**Comment by hamberluo** [comment] 2020-04-26 09:30
same error, any update?

**Comment by brianschardt** [comment] 2020-04-29 03:29
same error any updates??
I get an error when I have a parameter in the url
```
http://url.com/profile/1
```

**Comment by brianschardt** [comment] 2020-04-29 04:46
I have a good fix for this is an update is not push in the next few days I will publish my own temp package that others can pull from.

**Comment by brianschardt** [comment] 2020-04-29 06:08
here the forked package is. hopefully fluro fixes this soon.
https://pub.dev/packages/fluro_fork

**Comment by pmorenov** [comment] 2020-05-11 10:46
Hi @lukef 

This has becoming a blocking issue after updating to Flutter 1.17 and Fluro 1.6.3

@brianschardt 's fork (thanks!) seems to do the trick. Any chance for an official fix? 

Thank you

**Comment by teneon** [comment] 2020-05-30 14:45
I am using Flutter 1.17.1 and Fluro 1.6.3. In my case, both:
transitionType: TransitionType.nativeModal
and
transitionType: TransitionType.native
are preventing navigation from working. The error is output like this:
**The method 'dependOnInheritedWidgetOfExactType' was called on null.**

I ran into this error in Android Emulator, when i was testing the "Breaking Bapp" app:
[](https://github.com/EdsonBueno/breaking_bapp)

If you would like to take a look, simply
git clone (master branch) and try "flutter run" it. After it loads, click on any of the items in the "Characters" tab or in the "Quotes" tab. Because of this error navigation doesn't work, error is printed in the console instead.

If i comment out transitionType, it works. Any idea when this issue could be fixed?

Best regards,
Jim

**Comment by fatimahossny** [comment] 2020-05-30 14:57
You can fork it and update it like here https://github.com/theyakka/fluro/pull/166/commits/ca2e1d927f4b68e8824d5d5569925f2a4a6a587f
 it works fine for me as i need native transition

**Comment by mattetom** [comment] 2020-06-07 15:45
> here the forked package is. hopefully fluro fixes this soon.
> https://pub.dev/packages/fluro_fork

With this forks works correctly!
Thsnk you very much brianschardt

**Comment by zinwalin** [comment] 2020-06-08 04:20
> here the forked package is. hopefully fluro fixes this soon.
> https://pub.dev/packages/fluro_fork

awesome, thanks heaps.

**Comment by neckaros** [comment] 2020-07-17 13:21
Thanks for the fork!

Is the Fluro package still maintained? it seems like a pretty big issue with a simple solution available now for ~3 months

**Comment by tobytraylor** [comment] 2020-09-16 02:15
Looks like the last commit was around the same time this was opened.  Has this project been abandoned?

**Comment by lukepighetti** [comment] 2020-10-15 02:04
Please see https://github.com/theyakka/fluro/issues/184 for an update about the current status of `fluro`

**Comment by lukepighetti** [comment] 2020-10-16 02:18
I am not able to reproduce this. If this is still an issue would someone please post an MVCE and I'll reopen this?

**Comment by tobytraylor** [comment] 2020-10-18 16:33
Can somebody using Fluro Fork post on here when they have confirmed the latest build of fluro doesn't have this issue?

**Comment by lukepighetti** [comment] 2020-10-18 16:35
Conversely, if someone using Fluro Fork can reproduce this issue on the latest build of fluro, can you please give me as many details as possible so I can get this resolved?

**Comment by JagandeepBrar** [comment] 2020-10-24 02:30
@tobytraylor @lukepighetti I was using `fluro_fork` and just tried changing to the original `fluro` package and am still running into this issue.

My project is open source, and can be reproduced on the `v4.1.0+40100003` branch available here: https://github.com/CometTools/LunaSea/tree/v4.1.0%2B40100003

You don't need to add any of the modules/software to see the project, just open the drawer and attempt to open the settings page. You can view where I initialize the core router in `core/router.dart`, the settings router in `modules/settings/core/router.dart` and then each individual route definition is inside of that file. I can produce a MVCE if necessary, but it occurs specifically with `TransitionType.native` being used.

Also to note, I am also using the latest Flutter stable branch (1.22.2).

**Comment by JagandeepBrar** [comment] 2020-10-24 02:51
The issue is relatively easy to identify, using the generator, when it calls `matchRoute` on line 282, it passes a null BuildContext to the function (which is expected, since there is no context available).

Then on line 167 you attempt to access the platform type by calling `if (Theme.of(buildContext).platform == TargetPlatform.iOS) {`, which is what throws the error since `buildContext` is null.

The `fluro_fork` package remedied this by doing a check for a null context: `if (buildContext == null || Theme.of(buildContext).platform == TargetPlatform.iOS) {`. This could be considered non-ideal, since buildContext could be null for an Android device and it would still return a `CupertinoPageRoute`.

**Comment by lukepighetti** [comment] 2020-10-25 01:44
I'm unable to get `null` for `buildContext` except for when the first route `/` is pushed. So if you have seen `null` come in at another time I need a way to reproduce it otherwise I cannot provide assistance with this.

I pushed up https://github.com/lukepighetti/fluro/commit/e341fea57c7064f813e57ade807b2910f7cbdb2a but I'm concerned that if you're getting `null` values regularly then this will just break all transitions instead of providing relief on the first build.

**Comment by JagandeepBrar** [comment] 2020-10-26 15:55
@lukepighetti Here is a MVCE, everything is contained within the main.dart file: https://github.com/JagandeepBrar/fluro-issue-154-MVCE

Let me know if you need anything else on my side.

**Comment by JagandeepBrar** [comment] 2020-10-26 16:36
Is there even a need to separate the cases when using `TransitionType.native`?

When reading the [MaterialPageRoute](https://api.flutter.dev/flutter/material/MaterialPageRoute-class.html) class documentation, it says:

> A modal route that replaces the entire screen with a platform-adaptive transition.
> 
> For Android, the entrance transition for the page slides the route upwards and fades it in. The exit transition is the same, but in reverse.
> 
> The transition is adaptive to the platform and on iOS, the route slides in from the right and exits in reverse. The route also shifts to the left in parallax when another page enters to cover it. (These directions are flipped in environments with a right-to-left reading direction.)

Maybe this is new since fluro was originally developed, but testing it personally on iOS and Android devices, using `TransitionType.material` does in-fact keep the platform-specific transition type.

**Comment by JagandeepBrar** [comment] 2020-10-26 16:58
I have created a PR that simply removes the platform check and always uses `MaterialPageRoute`. I tested it on iOS 14.0-14.2 and Android 9-11: https://github.com/lukepighetti/fluro/pull/191

**Comment by lukepighetti** [comment] 2020-10-27 00:04
Merged, thank you so much!

**Closed** 2020-10-27 00:03 UTC
