### ISSUE TITLE
Route Guard and Rerouting

### ISSUE THREAD

**Issue by Benoss** [lukepighetti/fluro#73] opened 2018-11-12 10:01 UTC
Is there a way to implement a simple route guard?
For example if the user is not logged in (I can get the info from an inherited widget out of the context)
I want to  go to the /login page and in the other hand if I am on /login but the user is logged in I want to go to the root of the app.
I can't reroute during a Handler or I will get the error, which make sense:
```
I/flutter ( 3387): The following assertion was thrown building Builder(dirty):
I/flutter ( 3387): setState() or markNeedsBuild() called during build.
I/flutter ( 3387): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter ( 3387): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter ( 3387): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter ( 3387): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter ( 3387): Otherwise, the framework might not visit this widget during this build phase.
I/flutter ( 3387): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 3387):   Overlay-[LabeledGlobalKey<OverlayState>#46a1c](state: OverlayState#29c46(entries:
```
I could return the Login page instead of any other page but this looks weird as my Login page will be on the route / or any other route. I can clear the stack after logging in, but still a bit stange no?

How would you manage redirection?

**Comment by lukef** [comment] 2018-12-13 22:04
Couldn't you just implement this as regular dart code and check to see if the authentication has been met and return a "you need to log in" widget vs the one relevant for that route?

**Comment by smkhalsa** [comment] 2019-05-16 23:38
@lukef can you share any more about the filter interface and 2.0 in general?

My concern with just providing a login widget from the handler function is that the route state will be for the original route. One case where that could be problematic is once people start creating flutter apps for web since the url would not match the component.

**Comment by rizerzero** [comment] 2019-11-12 23:17
Still nothing about this ?

**Comment by nipunasudha** [comment] 2020-06-05 21:59
This is just sad, a critical part of a navigation library being ignored 😢

**Comment by DustinJSilk** [comment] 2020-09-17 09:33
Any updates on this yet?

**Comment by lukepighetti** [comment] 2020-10-16 02:39
Duplicate of https://github.com/lukepighetti/fluro/issues/112

**Closed by lukepighetti** 2020-10-16 02:39 UTC
Labels: question, stack overflow
