### ISSUE TITLE
We Need A Property That Provides The Current Route Page Properties

### ISSUE THREAD

**Issue by CNMathon** [lukepighetti/fluro#182] opened 2020-10-12 07:20 UTC
**Is your feature request related to a problem?**
 I'm always frustrated when I use the hook of fluro. For example, I need to implement a route blocker for a login feature. So we need to implement the logic to return to the login page if the token is null and the page name is not "login". However, we can't get the page name at all!

**Describe the solution you'd like**
We need a property that provides the current route page properties.

**Describe alternatives you've considered**
We have tried to use ```ModalRoute.of(context).settings.name``` in the Fluro route hook function to get the current route name, but it fails. It threw a report error. But it works fine when I trigger the above command via the button.

**Comment by lukepighetti** [comment] 2020-10-16 02:36
Duplicate of https://github.com/lukepighetti/fluro/issues/112

**Closed by lukepighetti** 2020-10-16 02:36 UTC
