### ISSUE TITLE
Are there plans to launch router interceptors?

### ISSUE THREAD

**Issue by Herryjoeson** [lukepighetti/fluro#92] opened 2019-03-12 06:53 UTC

**Comment by lukepighetti** [comment] 2020-10-16 01:18
Closing this because we're preparing for a major overhaul in `fluro 2.0` when we migrate to the new Pages / Navigator 2.0 API and I suspect the scope of this issue will change as a result. Please reopen if needed.

**Comment by lukepighetti** [comment] 2020-10-16 02:37
Duplicate of https://github.com/lukepighetti/fluro/issues/112

**Closed by lukepighetti** 2020-10-16 02:37 UTC
