### ISSUE TITLE
route path with params bug

### ISSUE THREAD

**Issue by machengda89** [lukepighetti/fluro#59] opened 2018-08-17 10:33 UTC
if defined routes has route with params, when this route executed, all defined route handle will be executed.

**Comment by lukef** [comment] 2018-12-13 22:07
I have not seen this. Do you have a minimal test case that reproduces this issue?

**Comment by lukepighetti** [comment] 2020-10-16 02:47
Closing because I cannot reproduce this

**Closed by lukepighetti** 2020-10-16 02:47 UTC
Labels: information needed
