### ISSUE TITLE
error:   TransitionType.native  or TransitionType.cupertino 

### ISSUE THREAD

**Issue by chinajuns** [lukepighetti/fluro#202] opened 2020-11-24 10:17 UTC
many tap,
eg:
xxxx.navigateTo(context, "/listView",transition: TransitionType.native);
error:
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Only valid value is 0: -1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:3987:44)
#2      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:737:15)
#3      CupertinoRouteTransitionMixin._startPopGesture (package:flutter/src/cupertino/route.dart:256:12)
#4      CupertinoRouteTransitionMixin.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:303:36)
...
Handler: "onStart"
Recognizer: HorizontalDragGestureRecognizer#f0dbf
  debugOwner: _CupertinoBackGestureDetectorState<dynamic>#85cd4
  start behavior: start

but:
xxx.navigateTo(context, "/listView",transition: TransitionType.inFromRight);

it's ok。

fluro:1.7.7

flutter:

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

**Comment by lukepighetti** [comment] 2020-11-24 13:53
Closing because I cannot reproduce it. Please re-open with an MVCE. Thanks!

**Closed by lukepighetti** 2020-11-24 13:53 UTC
