### ISSUE TITLE
How to pass multiple arguments

### ISSUE THREAD

**Issue by hkmsadek** [lukepighetti/fluro#98] opened 2019-03-30 23:51 UTC
Currently I am able to pass only one data like this 
`Navigator.pushNamed(context, "/about/23");`
and access it using 
```
router.define('/about/:id', handler: new Handler(handlerFunc: (BuildContext context, Map<String, dynamic> params) {
    return new AboutPage(params["id"][0]);
  }));

```

I want to pass multiple data like this 

`Navigator.pushNamed(context, "/about/23/newdata");`

How can I access this `newdata`? 
I tried 
```
router.define('/about/:id/:str', handler: new Handler(handlerFunc: (BuildContext context, Map<String, dynamic> params) {
    return new AboutPage(params["id"][0]);
  }));

```

It doesn't work. Thank you

**Comment by ChendayUP** [comment] 2019-04-02 06:15
params["str"].first can get newdata value

**Comment by lukepighetti** [comment] 2020-10-16 02:45
Closing because I cannot reproduce this

**Closed by lukepighetti** 2020-10-16 02:45 UTC
