### ISSUE TITLE
Automatic navigation to / route, when opening a keyboard

### ISSUE THREAD

**Issue by tobire** [lukepighetti/fluro#57] opened 2018-08-05 15:50 UTC
When I open a keyboard to type into a TextFormField, I get navigated to the target of the / route.

main.dart
```
class ImmoMatchApp extends StatelessWidget {
  final ImmoNavigator _navigator = new ImmoNavigator();

  @override
  Widget build(BuildContext context) {
    _navigator.initRoutes();
    return new MaterialApp(
      title: "ImmoMatch",
      onGenerateRoute: _navigator.router.generator,
    );
  }
}
```

ImmoNavigator:
```
class ImmoNavigator {
  static final ImmoNavigator _navigator = new ImmoNavigator._internal();
  factory ImmoNavigator() {
    return _navigator;
  }
  ImmoNavigator._internal();

  final Logger _logger = new Logger('ImmoNavigator');
  final Router router = new Router();

  initRoutes() {
    if (router.match('/') == null) {
      print('initializing routes');
      router.define(
        "/",
        handler: new Handler(
          handlerFunc: (BuildContext context, Map<String, dynamic> params) {
            print("Navigating to Boot");
            return new BootView();
          },
        ),
      );
      router.define(
        "/login",
        handler: new Handler(
          handlerFunc: (BuildContext context, Map<String, dynamic> params) {
            print("Navigating to Login");
            return new LoginView();
          },
        ),
      );
      router.define(
        "/signin",
        handler: new Handler(
          handlerFunc: (BuildContext context, Map<String, dynamic> params) {
            return new SignInView();
          },
        ),
      );
    }
  }
}
```

The TextFormField is in the LoginView and when I click on it, "Navigating to Boot" gets printed out.

**Comment by lukef** [comment] 2018-12-13 22:08
Do you have a minimal test case that produces this issue?

**Comment by callingmybluff** [comment] 2018-12-14 02:15
I have a PageController and I face the same problem as it mostly move the next page as soon as the keyboard pops up. Could it be a Flutter bug?

**Comment by ahelmel** [comment] 2019-01-04 15:38
I have the same issue. It was working when I had only one screen/page without any routes. But after I created a second screen/page and configured two routes it started to happen.

**Comment by DARdk** [comment] 2019-02-07 17:09
Any update on this issue? 
Happens for me when I am in: 
````
Flutter vs. 1.1.9 dev
Dart 2.1.1
````
Or in
````
Flutter vs. 1.2.1-pre.117
Dart 2.1.2
````
However, the "Bug" does NOT happen if I am in a previous version, such as: 
````
Flutter 0.11.5 dev
Dart 2.1.0,
````
In my case the route definition is build within a 
```
CupertinoTabScaffold > CupertinoTabBar
```

**Comment by panuavakul** [comment] 2019-02-09 12:30
@lukef Sorry for the late reply, I think this is the minimal test case with two screens based on the Flutter start project.

https://github.com/panuavakul/flutter_routing_bug

#### Step to reproduce
1) Put the break point in the handler
2) Run the project in iOS (have not test in Android)
3) Navigate to `MyOtherScreen` by tapping on the Floating Action Button
4) Tab on the `TextFormField` and the handler function should be called.

I am using Fluro and Redux in my project, and this cause a lot of problem when the router just randomly routing to the same screen resulting in the screen rebuilding, which cause the Redux's onInit function to be called and API and stuffs are called multiple times. If you need any other information please let me know. Thanks.

**Comment by alefcarlos** [comment] 2019-02-10 18:35
As @panuavakul commented above, I'm having the same problem, im my case I'm using flutter_bloc to implement BLoC pattern.

My app is open source [in this repo](https://github.com/alefcarlos/colecao_bolso_app/tree/bloc-pattern)

**Comment by hamedmonji** [comment] 2019-04-10 13:57
I had the same issue not why this was happening but I noticed that every time I taped on a TextFormField the build method was called.
The form was in a stateless widget with the key being there too I converted the widget to be a stateful widget and it solved the problem

**Comment by longdw** [comment] 2020-03-20 07:59
I have the same problmen, when TextField focused or lost focus and keyboard show or hide, the router Handler method entry repeated.

**Comment by longdw** [comment] 2020-03-20 08:57
> @lukef Sorry for the late reply, I think this is the minimal test case with two screens based on the Flutter start project.
> 
> https://github.com/panuavakul/flutter_routing_bug
> 
> #### Step to reproduce
> 1. Put the break point in the handler
> 2. Run the project in iOS (have not test in Android)
> 3. Navigate to `MyOtherScreen` by tapping on the Floating Action Button
> 4. Tab on the `TextFormField` and the handler function should be called.
> 
> I am using Fluro and Redux in my project, and this cause a lot of problem when the router just randomly routing to the same screen resulting in the screen rebuilding, which cause the Redux's onInit function to be called and API and stuffs are called multiple times. If you need any other information please let me know. Thanks.
> 
> Edit: It also happen when not using Fluro
> 
> ```
>           Navigator.push(context, MaterialPageRoute(builder: (context) {
>             return MyOtherPage();
>           }));
> ```
> 
> Maybe this is Flutter bug? or normal Flutter behaviour?
> 
> Edit2: Maybe this?
> [flutter/flutter#14124](https://github.com/flutter/flutter/issues/14124)

The bug has been fixed for a long time

**Comment by longdw** [comment] 2020-03-21 03:09
this is a flutter bug, [https://github.com/flutter/flutter/issues/37878](url), fluro no problem.
#152

**Comment by lukepighetti** [comment] 2020-10-16 02:41
Closing because there is nothing actionable.

**Closed by lukepighetti** 2020-10-16 02:41 UTC
Labels: information needed, investigating
