### ISSUE TITLE
Feature Request: Pre-route hook

### ISSUE THREAD

**Issue by byronferguson** [lukepighetti/fluro#102] opened 2019-05-06 15:25 UTC
Unless I've missed the ability, it would be convenient to have a pre-route hook for individual routes and for all routes.

If possible.

**Comment by lukef** [comment] 2019-05-06 17:05
This is coming in 2.0!

**Comment by GregorySech** [comment] 2019-06-04 11:44
Kinda off-topic but can `Filter` be used for route guarding?

**Comment by lukef** [comment] 2019-06-04 19:36
Yep! That's the intention. A Filter can either proceed, stop or error. So, if you wanted to do an auth guard you can "stop" and return the widget asking you to log in.

**Comment by rlee1990** [comment] 2020-02-17 18:27
Is there a time line for this?

**Comment by zero7u** [comment] 2020-05-29 07:56
When will ```fluro 2.0``` come? we also need the feather, thx bro~

**Comment by lukepighetti** [comment] 2020-10-16 02:36
Duplicate of https://github.com/lukepighetti/fluro/issues/112

**Closed by lukepighetti** 2020-10-16 02:36 UTC
Labels: enhancement
