### ISSUE TITLE
Public and private routes

### ISSUE THREAD

**Issue by rogueturnip** [lukepighetti/fluro#186] opened 2020-10-17 00:59 UTC
I was wondering if there is an example on how to handle public routes vs authenticated private routes?  Essentially having signup and sign-in pages public and the rest of the routes requiring some form of authentication to access them.

**Comment by lukepighetti** [comment] 2020-10-17 03:55
Duplicate of https://github.com/lukepighetti/fluro/issues/112

**Closed by lukepighetti** 2020-10-17 03:55 UTC
