### ISSUE TITLE
1.7.7 cannot be used in flutter 1.20.3

### ISSUE THREAD

**Issue by dashenxiwo** [lukepighetti/fluro#197] opened 2020-11-19 07:42 UTC
I can't compile it
pub.flutter-io.cn/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none  
          ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Linykun** [comment] 2020-11-23 07:26
I ran into the same problem.

**Comment by lukepighetti** [comment] 2020-11-24 13:49
Closed as duplicate of https://github.com/lukepighetti/fluro/issues/190#issuecomment-714425580

**Closed by lukepighetti** 2020-11-24 13:49 UTC
